# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tourme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tourme
pod 'Charts'

  target 'TourmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TourmeUITests' do
    # Pods for testing
  end

end
